#pragma config(Motor,  motorA,          motor,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
nMotorEncoder[motorA] = 0;

	while (nMotorEncoder[motorA] < 720)
		{
		motor[motorA] = 100; //Make the motor turn! :D
		}
	motor[motorA] = 0;

}
